name: Build and Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-deploy:
    if: github.repository == 'profectus-engine/profectus-docs'
    runs-on: docker
    steps:
      - name: Setup RSync
        run: |
          apt-get update
          apt-get install -y rsync

      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install --frozen-lockfile
          yarn run generate
          yarn run build

      - name: Deploy 🚀
        uses: https://github.com/JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: pages # The branch the action should deploy to.
          folder: docs/.vitepress/dist # The folder the action should deploy.
